### ISSUE TITLE
Spettro della vita

### ISSUE THREAD

**Issue by auron95** [giove91/server-lupus#11]
Proposte di cambiamento last minute da testare.

- [ ] Lo Sciamano rimuove il potere.
- [ ] I Negromanti vivi possono agire sugli Spettri (vivi e morti).
- [x] I Negromanti riescono a cambiare il potere della Vita. Questo causa la morte dello Spettro.
- [x] Se lo Spettro della vita muore, allora diventa uno Spettro Vuoto.
- [x] Se un Esorcista agisce su una persona sulla quale ha agito lo Spettro della Vita, il potere di quest'ultimo ha effetto.
- [x] Bisogna anche ~~cambiare il wording di~~ eliminare SoulConsuptionEvent.

**Comment by SashaIr** [comment]
Lo Sciamano rimuove il potere e blocca l'assegnazione di nuovi poteri. Ovvero, lo Spettro la mattina seguente si sveglia stordito, confuso, e vuoto, no matter what.

**Comment by auron95** [comment]
L'Esorcista invece ha effetto, come al solito, anche sugli spettri vivi.
